FORMAT: 1A
HOST: https://yasuhiro-api.herokuapp.com/

# Yasuhiro API

コンテンツとしてのYasuhiro.

## 戯言 Collection [/nonsenses]

### すべての戯言を取得 [GET]

+ Response 200 (application/json)

        [
            {
                "body": "日報書いてない人は、仕事してない。",
                "created_at": "2015-08-05T08:40:51+09:00",
                "confidential": false
            }
        ]
